### ISSUE TITLE
[NUCLEO_F207ZG] Symbol 'id_init_declarator_list_opt' used, but not defined as a token or a rule

### ISSUE THREAD

**Issue by gautaz** [ARMmbed/mbed-js-example#11]
Hello,

I'm trying to build the project for the target NUCLEO_F207ZG and it currently fails with:

```
ERROR: /usr/local/lib/python2.7/site-packages/pycparser/c_parser.py:630: Symbol 'id_init_declarator_list_opt' used, but not defined as a token or a rule
ERROR: /usr/local/lib/python2.7/site-packages/pycparser/c_parser.py:709: Symbol 'declaration_specifiers_no_type_opt' used, but not defined as a token or a rule
ERROR: /usr/local/lib/python2.7/site-packages/pycparser/c_parser.py:714: Symbol 'declaration_specifiers_no_type_opt' used, but not defined as a token or a rule
ERROR: /usr/local/lib/python2.7/site-packages/pycparser/c_parser.py:719: Symbol 'declaration_specifiers_no_type_opt' used, but not defined as a token or a rule
WARNING: /usr/local/lib/python2.7/site-packages/pycparser/plyparser.py:42: Rule 'specifier_qualifier_list_opt' defined, but not used
WARNING: /usr/local/lib/python2.7/site-packages/pycparser/plyparser.py:42: Rule 'declaration_specifiers_opt' defined, but not used
WARNING: There are 2 unused rules
WARNING: Symbol 'id_init_declarator' is unreachable
WARNING: Symbol 'id_init_declarator_list' is unreachable
WARNING: Symbol 'specifier_qualifier_list_opt' is unreachable
WARNING: Symbol 'declaration_specifiers_opt' is unreachable
ERROR: Infinite recursion detected for symbol 'direct_declarator'
ERROR: Infinite recursion detected for symbol 'declaration_specifiers_no_type'
Traceback (most recent call last):
  File "tools/generate_pins.py", line 247, in <module>
    main()
  File "tools/generate_pins.py", line 237, in main
    pins = enumerate_pins(pins_file, ['./tools'] + list(includes), defines)
  File "tools/generate_pins.py", line 154, in enumerate_pins
    parser=GnuCParser())
  File "/usr/local/lib/python2.7/site-packages/pycparserext/ext_c_parser.py", line 47, in __init__
    debug=yacc_debug, write_tables=False)
  File "/usr/local/lib/python2.7/site-packages/pycparser/ply/yacc.py", line 3426, in yacc
    raise YaccError('Unable to build parser')
pycparser.ply.yacc.YaccError: Unable to build parser
```

Any idea of what may cause this error?

**Comment by janjongboom** [comment]
I had to massage the PinNames.h file for this board to get it to work with generate_pins.py

Replace 'build/jerryscript/targets/mbedos5/mbed-os/targets/TARGET_STM/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/PinNames.h' by [this file](https://gist.github.com/janjongboom/135c486acc2e8f6063912fcafff4c8e4).

However... Then it still does not compile:

```
[Error] arm_math.h@5842,23: 'sqrtf' was not declared in this scope
[ERROR] In file included from ./mbed-os/rtos/rtx5/TARGET_CORTEX_M/core_cm.h:34:0,
                 from ./mbed-os/rtos/rtx5/TARGET_CORTEX_M/rtx_lib.h:33,
                 from ./mbed-os/rtos/mbed_rtos_storage.h:43,
                 from ./mbed-os/rtos/rtos.h:30,
                 from ./mbed-os/mbed.h:38,
                 from ../../../source/main.cpp:3:
./mbed-os/cmsis/arm_math.h: In function 'arm_status arm_sqrt_f32(float32_t, float32_t*)':
./mbed-os/cmsis/arm_math.h:5842:23: error: 'sqrtf' was not declared in this scope
       *pOut = sqrtf(in);
```

Which is weird because mbed OS 5.5 blinky compiles fine, and I don't see anything obvious in the Jerryscript drivers for mbed OS which might reference this file...

**Comment by gautaz** [comment]
Strange, I am currently using the modified version of `PinNames.h`:

```
✔ ~/dev//nucleo/mbed-js-example/build/jerryscript/targets/mbedos5/mbed-os [mbed_lib_rev142|✚ 1] 
15:41 $ git diff
index a2be49100..06f91e210 100644
--- a/targets/TARGET_STM/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/PinNames.h
+++ b/targets/TARGET_STM/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/PinNames.h
@@ -37,26 +37,19 @@
 extern "C" {
 #endif

-typedef enum {
-    ALT0  = 0x100,
-    ALT1  = 0x200,
-    ALT2  = 0x300,
-    ALT3  = 0x400,
+int ALT0  = 0x100;
+int ALT1  = 0x200;
...
```

But I am still getting the same error than on my first post.
Did I miss something?

**Comment by janjongboom** [comment]
@gautaz, not sure... I've tested with https://github.com/jerryscript-project/jerryscript/pull/1982 and that works fine, so can you try:

```
$ cd build/jerryscript
$ git remote add janjon git@github.com:janjongboom/jerryscript.git
$ git fetch janjon
$ git checkout janjon/update_mbed_os_5.5

$ cd targets/mbedos5
$ mbed deploy
```

**Comment by gautaz** [comment]
@janjongboom, OK, now I'm getting a result close to yours (apart from the additional `DEFAULT_STACK_SIZE` error):

```
Compile [  4.2%]: main.cpp
[Error] arm_math.h@5842,23: 'sqrtf' was not declared in this scope
[Error] main.cpp@40,41: 'DEFAULT_STACK_SIZE' was not declared in this scope
[ERROR] In file included from ./mbed-os/rtos/rtx5/TARGET_CORTEX_M/core_cm.h:34:0,
                 from ./mbed-os/rtos/rtx5/TARGET_CORTEX_M/rtx_lib.h:33,
                 from ./mbed-os/rtos/mbed_rtos_storage.h:43,
                 from ./mbed-os/rtos/rtos.h:30,
                 from ./mbed-os/mbed.h:38,
                 from ../../../source/main.cpp:3:
./mbed-os/cmsis/arm_math.h: In function 'arm_status arm_sqrt_f32(float32_t, float32_t*)':
./mbed-os/cmsis/arm_math.h:5842:23: error: 'sqrtf' was not declared in this scope
       *pOut = sqrtf(in);
                       ^
../../../source/main.cpp: At global scope:
../../../source/main.cpp:40:41: error: 'DEFAULT_STACK_SIZE' was not declared in this scope
 rtos::Thread jsThread(osPriorityNormal, DEFAULT_STACK_SIZE*2);
                                         ^~~~~~~~~~~~~~~~~~
```

**Comment by janjongboom** [comment]
@gautaz Yep, the stack size macro is fixed upstream already. `npm update mbed-js-gulp` should work.

Although I still don't know why it fails to compile on this target with the `sqrtf` error.

**Comment by gautaz** [comment]
@janjongboom You're right, I have exactly the same result as yours now.

I guess the default toolchain is GCC_ARM and I was wondering if there was a way to test with another toolchain by passing the right arguments to gulp?

**Comment by janjongboom** [comment]
@gautaz Yes, change [this file](https://github.com/jerryscript-project/jerryscript/blob/master/targets/mbedos5/Makefile#L85), then remove the `.mbed` file and rebuild.

**Comment by gautaz** [comment]
Done, the `.mbed` file has been updated accordingly after the build:
```
14:26 $ cat ./build/jerryscript/targets/mbedos5/.mbed
ROOT=.
TOOLCHAIN=ARM
TARGET=NUCLEO_F207ZG
```

But it doesn't seem to be taken into account as the build log still displays:

```
mbed target NUCLEO_F207ZG
[mbed] NUCLEO_F207ZG now set as default target in program "mbedos5"
mbed compile -j0 --source . --source ../../ --source ../../../source --build ../../../out/NUCLEO_F207ZG -D "CONFIG_MEM_HEAP_AREA_SIZE=(1024*16)" -t GCC_ARM
Building project mbedos5 (NUCLEO_F207ZG, GCC_ARM)
```

@janjongboom Do you have any idea why it still seems to be compiling with the `GCC_ARM` toolchain?

**Comment by janjongboom** [comment]
@gautaz Also remove [this line](https://github.com/jerryscript-project/jerryscript/blob/master/targets/mbedos5/Makefile#L52).

**Comment by gautaz** [comment]
Not sure about all this but my current understanding is that during the compilation, the `arm-none-eabi-g++` compiler uses the `math.h` header located at `build/jerryscript/jerry-libm/include/math.h` and not the native `arm-none-eabi-g++` header.

Looking at this header, I see no definition for `sqrtf` (there is one for `sqrt` but no floating point version).

@janjongboom Perhaps you have more insight on this?

**Comment by janjongboom** [comment]
@gautaz Good hint. I managed to build like this:

```
$ mv ./build/jerryscript/jerry-libm/include/math.h ./build/jerryscript/jerry-libm/include/math.h.old
```

Then apply the following diff to mbed-os: [diff](https://gist.github.com/janjongboom/374e55e6349ef31e944919484283c36a).

Not sure if it will actually run due to the pinname change shenanigans.

**Comment by janjongboom** [comment]
Fixed upstream in https://github.com/jerryscript-project/jerryscript/pull/1988

**Comment by janjongboom** [comment]
Re-opening because the pin issues are not solved.

**Comment by gautaz** [comment]
@janjongboom The build is OK with the `jerry-libm/include/math.h` header removal and with your patch.

Many thanks !
Do you have any idea of how much time it generally takes for the upstream to merge this?

**Comment by janjongboom** [comment]
@gautaz Probably a day or two at the most :-)

**Comment by gautaz** [comment]
Spring cleaning time!
There is no need to keep this issue anymore, feel free to reopen a new one if needed.
