### ISSUE TITLE
DigitalIn not working?

### ISSUE THREAD

**Issue by rvdende** [ARMmbed/mbed-js-example#13]
Hey I just got mbed js working on the ST-Nucleo-F411RE

I'm experimenting with the basics through the serialport REPL.

These all work: (ps I wish there was documentation for the JS api syntax.)

```
var led = new DigitalOut(LED1)

led.write(1)
led.write(0)

//// ------------------------------------------

var button = InterruptIn(PC_13);
button.fall(function() { led.write(1) } );
button.rise(function() { led.write(0) } );

//// ------------------------------------------

var ain = AnalogIn(A0);
ain.read();
```

But when I try to read a logiclevel using:

`var mypin = new DigitalIn(PC_13); `

I get "Running failed..."

Any idea why?

**Comment by rvdende** [comment]
Okay I found it, and got it working. Here is a commit https://github.com/bitlabio/jerryscript/commit/65b92b30582c6e3395405fd0280a1f4564ab19e5
lets see if I can make a PR

**Comment by janjongboom** [comment]
@fluentart Awesome, thanks for the PR, will comment in the other thread.
