### ISSUE TITLE
The output file (.hex) of this example is too big for NRF52_DK target

### ISSUE THREAD

**Issue by pmcalabrese** [ARMmbed/mbed-js-example#3]
The output file (.hex) of this example is 1.3 MB. Is that correct? Seems a bit too big to me ... Am I doing something wrong? Do you get the same result? Anyone experiencing the same?

**Comment by pmcalabrese** [comment]
Am I the only one experiencing this?

**Comment by janjongboom** [comment]
@pmcalabrese Define 'too big'? It flashes and runs fine on the nRF52-DK. The hex files are always bigger than bin files. Actual RAM and ROM usage can be observed by looking at the build logs.

(But yeah, shipping the whole JS VM is not small ;-)).

**Comment by pmcalabrese** [comment]
because i cannot fin the bin file i thought was the .hex file that i had to put in the NRF52 ROM, and its ROM is smaller then 1.3 MB.

**Comment by janjongboom** [comment]
@pmcalabrese Just drag the .hex file onto the board (mounted as mass-storage) and it'll flash just fine. :-)

**Comment by pmcalabrese** [comment]
This is what happen when i drug the .hex file onto the board

![image](https://cloud.githubusercontent.com/assets/1509241/21908245/42e85ece-d913-11e6-911e-5fe1acab0904.png)

**Comment by janjongboom** [comment]
@pmcalabrese The size of the hex file seems normal... And it flashes fine on my nRF52-DK. Maybe the bootloader needs updating? I'm on the latest [JLINK version](https://www.nordicsemi.com/eng/nordic/Products/nRF52-DK/nRF5x-OB-JLink-IF/52275), but haven't heard from anyone else with this problem.

Bootloader upgrade instructions are [here](https://developer.mbed.org/platforms/Nordic-nRF52-DK/). Interesting to see if that makes a change. If not, what's the board's revision?

**Comment by pmcalabrese** [comment]
@janjongboom  All sorted, now it blinks, I had the MBED bootloader, but instead I need the of the JLINK version. Thank you, very helpful!

**Comment by pmcalabrese** [comment]
@janjongboom  Bit OT, where can I find documentation for the API like `DigitalOut` ?

**Comment by janjongboom** [comment]
@pmcalabrese We follow the C++ API for most 'simple' APIs (like DigitalOut, I2C, etc.). See the [handbook](https://developer.mbed.org/handbook/Homepage#analog-i-o) for more info.
