### ISSUE TITLE
Compiling mbed-js-exemple from git-bash (git for windows)

### ISSUE THREAD

**Issue by LMESTM** [ARMmbed/mbed-js-example#4]
I'm trying to follow-up README steps using my windows machine, using git-bash.exe from "git for windows" - and I face several issues.

Is there a plan to support similar setup as mine, or is there another recommended environment for windows machine users ? 

Some notes about the 2 issues I faced:

1st issue is that the gulp-run tries to execute wth cmd.exe as we're running on windows, but I'd like it to be run in shell:

`[10:14:37] 'make-build-dir' errored after 189 ms
[10:14:37] Error: Command `mkdir -p ./build/source` exited with code 1
    at ChildProcess.handleSubShellExit (C:\Data\Workspace\repl-js\node_modules\gulp-run\command.js:166:13)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
$ mkdir -p ./build/source
`

2nd issue (in case I work-around previous one by forcing shell) is with the Makefile (build/jerryscript/targets/mbedos5/Makefile). When trying to compute the list of source it comes up with a wrong list of "EXTRA_SRC" source directories, most probably due to windows as well. 

If I force the list of directories, I can successfully build. So we're not so far to have it working.

**Comment by janjongboom** [comment]
@LMESTM Have not spent any time making this build in Cygwin/Windows yet, but should be doable. I'll throw some time at it next week.

**Comment by janjongboom** [comment]
Fixed in https://github.com/ARMmbed/mbed-js-gulp/pull/14!
