### ISSUE TITLE
Support for TI Launchpad cc1310F128

### ISSUE THREAD

**Issue by roboflank** [ARMmbed/mbed-js-example#7]
Greetings, 
Great work on the library.
Am working on a arm using the cc1310 launchpad kit, Am really interested to implement the project on it. I know this boils down to platform support for mbed, but kindly advice for any work around available or in mind. 
Regards. 
Denzel Wamburu.

**Comment by janjongboom** [comment]
@denzelwamburu Yes, mbed support would be required first, but even then the launchpad comes with too little RAM and flash to be able to run JerryScript.

**Comment by roboflank** [comment]
@janjongboom thank you.
Is there any support for any Texas instruments?

**Comment by janjongboom** [comment]
@denzelwamburu There are no TI boards supporting mbed OS 5 at the moment.
