### ISSUE TITLE
How to include mbed external lib ?

### ISSUE THREAD

**Issue by cyliangtw** [ARMmbed/mbed-js-example#9]
In ARM mbed architecture, I could include RF lib for 6LowPan, include mbed-client lib for Cloud connection and so on.
Now, how could I include mbed external lib in JavaScript sample ?
For ex, I want to create one socket connection through WiFi, how could I include esp8266 lib ?

**Comment by janjongboom** [comment]
It's not as straight forward as I'd like it to be, but:

1. Add the library like you'd normally do (`mbed add`).
1. Create a C++ <> JS wrapper ([more info](https://developer.mbed.org/blog/entry/Using-mbed-libraries-with-JerryScript/)).
1. Use the wrapper from JS.

Wrappers can be small, f.e. here's one for easy-connect: https://github.com/ARMmbed/mbed-js-easy-connect

**Comment by cyliangtw** [comment]
Thanks.
Refer to `mbed-js-simple-client-example`, it needs both of `mbed-js-simple-client` and `mbed-js-easy-connect` wrapper libs.
1. `package.json` only mentioned `mbed-js-simple-client`, how could `"npm install"` get mbed-js-easy-connect ?
2. `gulp` could auto generate `targets\mbedos5\js` and `targets\mbedos5\source`, never need add `JERRY_USE_MBED_LIBRARY(...)` manually, right ?

**Comment by janjongboom** [comment]
mbed-js-simple-client-example is not complete at the moment, as I had trouble fitting both mbed Client and JerryScript in 512K RAM. But yeah, just add a library to package.json and then run `npm install` to install.

On 2. yes, see mbedjs.json. It tells the build script which files to load (which then do the JERRY_USE_MBED_LIBRARY internally).

**Comment by janjongboom** [comment]
@cyliangtw Also, see my work in https://github.com/janjongboom/mbed-js-wrapper-generator

**Comment by cyliangtw** [comment]
I created one new lib wrapper and add into package.json as below:
 ` "dependencies": {"nvtLed-js": "/cygdrive/c/ARM_mbed/examples/mbed-js-example/build/jerryscript/targets/mbedos5/source/nvt-led"},`
Then, run  `gulp --target=NUMAKER_PFM_NUC472`, the generated `/source/main.cpp`  doesn't add this new lib.
So, I modify /source/main.cpp manually. After run  `gulp --target=...`, main.cpp rollback. Still not include my new lib.
I try another way, just to run `make BOARD=...` at `\examples\mbed-js-example\build`, still can't success as below:

```
7\lib\site-packages (from pycparserext->-r tools/requirements.txt (line 3))
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\ARM_mbed\examples\mbed-js-example\build\jerryscript\targets\mbedos5>
```

**Comment by janjongboom** [comment]
@cyliangtw Did you run `npm install` after adding it to dependencies? Also, is `nvtLed-js` the name that is in `package.json` of the wrapped module? They need to match.

To do this all in one go, in general I do:

```
npm install /cygdrive/c/ARM_mbed/examples/mbed-js-example/build/jerryscript/targets/mbedos5/source/nvt-led --save
```

**Comment by cyliangtw** [comment]
Thanks, I miss `npm install` for this new lib.

**Comment by janjongboom** [comment]
@cyliangtw Great. I'm publishing an article on this today or Monday, so that should help people getting started.
